src/App.jsx
src/views/omview.jsx

Decscription gjorde igeom vanlig p taggar, även gjort ett eget tag för kontakt med card feturen, samtidigt som lagt en möjlighet för en bild. Finns även en Påsk egg.

OmView gjord

---

src/App.jsx
src/components/MainMenu.jsx
src/views/AboutView.jsx

Löst konkift med att build om projekt inget fel uppkommit.

Conlift löst med OmView

---

src/App.jsx
src/views/TheaterView.jsx

Har byggt sidan enligt wireframe, dock utan användarnamn/login-delen (dvs betalning), tänker vi addar det senare. Nu har vi en grund här som är tydlig.

Overview of seats and buttons added

---

src/sass/own-styling.scss
src/views/StartView.jsx

Försökte även göra den så lik wireframe som möjligt

Fix aspect ratio in StartView

---

src/components/MainMenu.jsx

Nav.Links still appear inline with Nav.Brand when expanded (desktop)

Implements routing from wireframe in navbar

---

src/views/CancelView.jsx

Inte 100% som wireframe, men tror denna lösningen är bättre.
Kommentera om du inte anser lösningen tillfredsställande.

Lade till en konfirmationsbox och tog bort img i CancelView

---

WebReact/src/sass/load-and-modify-bootstrap.scss

- Chooses stronger color variables, no more warnings
- Centers bg at >= lg

Fixes color warnings and centers bg

---

webapi/Controllers/MoviesController.cs

Nu returneras en stor mängd information om varje film. När det gäller json datan från db så får man hantera de på olika sätt beroende på om det ska vara en sträng eller en lista. 
Den enda som inte är på plats är reviews, men det kan vi implementera i ett senare skede.

Extended the rendering of movie details

---

webapi/Controllers/MoviesController.cs

Movieviewapi

---

webapi/Controllers/TheatersController.cs
webapi/Entities/Seat.cs

Skapar en endpoint som visar:
- TheaterId
- Namnet på theater
- Seats på theater: hur många, vilket nummer de har och vilken rad de är på
- Om de är lediga eller upptagna

Theater api

---

webapi/Controllers/ScreeningsController.cs
webapi/Controllers/TheatersController.cs
webapi/Entities/Booking.cs

- Endpoint för att ange en screening och returnera bokade säten för screening samt vilken film det gäller
- Städade upp i modellen för bookings
- Tog bort isBooked på theaterapi för att den ger oss ingen relevant information

Addendpointscreenings

---

.vscode/tasks.json

Ctrl+Shift+P -> Tasks: Run Task -> run. When .NET API is up, manually open 'localhost:5173/' in browser.

Custom task 'run' in VS Code

---

webapi/Controllers/BookingsController.cs
webapi/Controllers/ScreeningsController.cs
webapi/Entities/Booking.cs
webapi/ViewModels/MakeBookingModel.cs

- Möjligt att nu göra en post som skapar en bokning. Först skapas user utifrån angiven email, sen bokning och slutligen en lista med seatbookings (seat id, price category).

Skapa bokning-endpoint

---

WebReact/src/views/MovieView.jsx

- Adjusts YouTube iframe sizing to viewport
- Modifies embedded sizing
- Removes unused class

YouTube iframe size adjusts to viewport

---

WebReact/src/utilsAndHooks/date-formatter.js
WebReact/src/views/MovieView.jsx
webapi/Controllers/ScreeningsController.cs

- Changes main function name
- Screenings accessed
- Implements screening DateTimes in MovieView, various fixes

Implements DateTime in MovieView, modifies ScreeningsController

---

webapi/Controllers/BookingsController.cs
webapi/Controllers/Utilities/BookingNumberGenerator.cs

- post do not anymore require clientside booking num and booking date, instead generated by api

Modify booking controller

---

WebReact/src/sass/own-styling.scss
WebReact/src/views/MovieView.jsx
WebReact/src/views/TheaterView.jsx

- Changes button to Link, spaced evenly
- Changes some colors
- Removes unused import
- Implements movie details
- Implements movie detailsvertically, tyle movie details
- Implements movie details, horizontally

Movie details horizontally

---

webapi/Controllers/BookingsController.cs
webapi/Controllers/Utilities/BookingNumberGenerator.cs

* changed to capital letters for the letters
* also added a check to make sure that the generated number does not already exist in the database

Modifynumbergenerator

---

WebReact/src/sass/own-styling.scss
WebReact/src/views/MovieView.jsx
___sprint_reviews___/SPRINT1.md

- Implements breakpoint for inline/block
- Added sprint retrospective 1

Sprint Retrospective 1

---

.gitignore
WebReact/src/views/StartView.jsx
webapi/appsettings.Development.json

added the filtering for droping down the bar. it filiters using the usestate that is chosen and then looks at id,movie,images.

Added func for the drop down bar.

---

webapi/Controllers/UsersController.cs
webapi/Controllers/Utilities/PasswordEncryptor.cs
webapi/Entities/User.cs

* Kan nu posta ny user 
* Lösenordet krypteras via SHA256 och salt adderas

Create user with hashed password

---

WebReact/src/utilsAndHooks/date-formatter.js
WebReact/src/utilsAndHooks/formatter.js
WebReact/src/views/MovieView.jsx

- Fixes correct delimiter in actor list
- Put function in formatter.js
- Function in formatter.js

Fixes delimiter in actor list

---

WebReact/src/views/TheaterView.jsx
webapi/Controllers/ScreeningsController.cs

Rewrite of TheaterView!
En hel del buggar fixade.

Theater view rewrite

---

webapi/Controllers/BookingsController.cs

ändrade exception hantering och medelanted vid badRequest

Avbokning endpoint

---

WebReact/src/App.jsx
WebReact/src/components/ShowSeats.jsx
WebReact/src/views/StartView.jsx
WebReact/src/views/TheaterView.jsx

Såg ännu en react video och lärde mig lite nytt

TheaterView new technics implemented

---

WebReact/src/App.jsx
WebReact/src/components/MainMenu.jsx
WebReact/src/utilsAndHooks/rest.js
WebReact/src/views/LoginView.jsx
WebReact/src/views/StartView.jsx
webapi/Controllers/SessionsController.cs
webapi/Controllers/UsersController.cs

Userrole global

---

.gitignore
WebReact/src/views/TheaterView.jsx
webapi/Controllers/UsersController.cs

Fixar register i usersController
Uppdaterar gitignore - Jag hade fel innan. hade behövt en ´*´ innan Properties. Nu tar jag det säkra före det osäkra.
Fixar även det som var tänkt från början, hantering av email i TheaterView när man är inloggad.

Theater view user role implement

---

webapi/Controllers/SessionsController.cs
webapi/Controllers/UsersController.cs
webapi/Controllers/Utilities/UserRole.cs
webapi/Middleware/UserRoleMiddleware.cs

var tvungen att göra en hotfix för att få in min andra pr med ACL

changed name of enum

---

WebReact/src/views/LoginView.jsx
webapi/Controllers/UsersController.cs

Kontrollerar att man blir inloggad innan man redirectar till /

Bug hunting login view

---

WebReact/src/components/MainMenu.jsx
WebReact/src/main.jsx
WebReact/src/views/AdminView.jsx
webapi/Controllers/BookingsController.cs

If "admin" userrole can press Admin on navbar. From there, get information about specified booking. 
Styling very basic for now.

Admin view

---

WebReact/src/components/MainMenu.jsx

Förlåt för att jag skrev usel kod i helgen. Borde ha testats mer.

Kollar bredden på window

---

webapi/Controllers/BookingsController.cs

Fixar buggen att eposten skickar fel tid.

Fixade till screening tid I eposten

---

webapi/Controllers/GenericController.cs
webapi/Controllers/UsersController.cs
webapi/Controllers/Utilities/UserRoleAuthoritization.cs

added authorization to user controller

Acl security

---

WebReact/src/utilsAndHooks/formatter.js
WebReact/src/views/MovieView.jsx

- A bit better scrolling behavior...
- Fixes formatter Imorgon

A bit better scrolling behavior

---

WebReact/src/views/AdminView.jsx

Enligt samma "mall" som login, skapa konto osv. Quick fix.

Stylat admin 
